### ISSUE TITLE
Missing `<` if it occurs before a link

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-cc#333]
```adoc
==== Initialization of the Status registry

This specification updates <<RFC5545>> by adding a Status value registry to the iCalendar Elements registry
located here: <https://www.iana.org/assignments/icalendar> and initializing it as per <<RFC5545>>.

located here: <hello>.
```

Notice that the `<` symbol only shows up for the second instance. The first `<` is lost.

<img width="482" alt="Screenshot 2024-12-04 at 11 39 01 AM" src="https://github.com/user-attachments/assets/5dd59d52-bc28-4a90-a8ca-58221179f8c7">

Document:
* https://github.com/CalConnect/cc-subscription-upgrade

**Comment by opoudjis** [comment]
That's Asciidoctor being opinionated: it is grabbing the < as part of the hyperlink.

https://github.com/asciidoctor/asciidoctor/blob/0908d45fef9350dbdc68d312ae2b4e8d63bda091/lib/asciidoctor/rx.rb#L518

Which means there is nothing I can do about it, it's done as part of Asciidoc parsing before I get to the document.

To work around this, insert a ZWJ between < and the http:

````
located here: <&#x200d;https://www.iana.org/assignments/icalendar> and 
````

![Screenshot 2024-12-13 at 14 44 23](https://github.com/user-attachments/assets/6eae64e9-9421-49d9-b991-c2057195043e)
